# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 356deab09ef9b145f4e0c15de538e9d67d0f992a74d7f113771e196aa5ff98cb566c86af868bcf79f397d78375e252f176a9649a8c7b9e0ed824d392f8897e26

test:
  secret_key_base: d41338952556c744a3907ca85bdb5fd07b166a70dc89d38d39e1dba3b9845124b59fd1247f417417b9ef42bea2c66ee974adf22d7ac0b85532d1d4d344e17f04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
